== Selección de la Vida de John Crook

He sido presionado a menudo en espíritu a escribir
la siguiente historia acerca de mi vida,
para que el mundo, así como mis amigos y conocidos,
puedan conocer los tratos del Señor conmigo desde mis tiernos años,
tanto para la consolación de los santos,
como para la información e instrucción de todos aquellos a cuyas manos llegue este relato.
Pero por encima de todo,
deseo que el Dios de mi vida sea temido y exaltado en los corazones,
y por las vidas santas de todos los hijos e hijas de los hombres para siempre.

Nací al norte del país,
de padres que eran de la religión común de los tiempos en que vivieron.
Fui criado por ellos y a la manera de ellos,
hasta aproximadamente los diez u once años. Durante ese
tiempo experimenté muchas pruebas en mi hombre interior,
y con frecuencia oraba en lugares apartados según surgían las palabras en mi mente,
y según aprendía oraciones sin un libro.
Pese a eso, permanecían dentro de mí muchos y fuertes combates,
los cuales continuaban apareciendo por varios meses.
En una ocasión que se destaca entre las demás,
estuve a punto de ser vencido y cerca de consentir que el
diablo me incitara (mediante un esfuerzo poderoso y violento),
a rendir toda mi resistencia y oposición a él. Pero de repente,
se levantó en mí un poder y vida que se opuso y rechazó al enemigo,
haciendo que mi espíritu dijera dentro de mí, con mucho denuedo y valor: "`No te serviré,
Satanás, sino que serviré al Señor Dios del cielo y de la tierra,
sin importar lo que sufra o sea de mí.`" Recuerdo bien que mi lengua
pronunció esto audiblemente y con mucha vehemencia y resolución,
en completo consentimiento con lo que se estaba hablando internamente en mi corazón,
y en oposición y contradicción al espíritu maligno
que fuertemente me tentaba a rendirme a la maldad.
Después de esto, me asusté al considerar estos dos esfuerzos contrarios en mi espíritu,
y qué podrían significar, pues yo nunca había oído a nadie hablar de tales cosas.
Y estaba especialmente sorprendido al considerar,
qué sería esa voz que habló con semejante autoridad en mí y le
ordenó hablar a mi lengua audazmente en conformidad con ella,
y en contra de lo que casi me había forzado a consentir sus malas intenciones y sugerencias.
Pero por la tranquilidad y alivio que sentía en mi interior,
concluí que había sido el Señor quien me había ayudado en tan grande prueba.

Recuerdo que después de esto, cuando era tentado o atribulado en mi mente,
me iba a algún rincón o lugar secreto y oraba a Dios.
Y cuando había cometido pecado y maldad, y después era afligido,
oraba a Dios pidiéndole Su fuerza contra esto.
Me di cuenta de que cuando estaba solo,
Él trataría conmigo todas y cada una de mis acciones,
pues mis pecados se refrescaban en mi memoria y estaban tan puestos delante de mí,
que no podía sacarlos de mi vista.
Entonces me esforzaba por entrar en algún lugar privado para orar y llorar,
y le prometía a Dios y pactaba en secreto con Él,
que nunca haría lo mismo de nuevo si Él me perdonaba
los pecados y me ayudaba en el futuro.
Pero a pesar de todo esto,
los males prevalecían en mí y no podía cumplir mis promesas a Dios.
Entonces venía aflicción sobre mi espíritu, y a menudo me lamentaba y andaba pesadamente.
No me deleitaba en el juego o en los pasatiempos que veía que otros niños disfrutaban,
lo que con frecuencia me hacía concluir en mi mente,
que ellos estaban en una mejor condición que la mía,
y que definitivamente Dios estaba enojado conmigo,
lo cual era la causa de que me corrigiera así. Pues
yo veía que los otros niños estaban felices y alegres,
pero que yo no tenía paz.
Sin embargo, a veces encontraba tranquilidad y estaba alegre,
pero rara vez duraba sin que se entremezclara la aflicción. También experimenté
muchas revelaciones en mi mente acerca del cielo y del infierno,
de hombres malos y buenos, las cuales a veces me sorprendieron mucho.
Y vi que muchos de los sacerdotes en aquellas partes eran profanos,
pues se entregaban a varios tipos de maldad.

Cuando tenía unos diez u once años fui a Londres,
y estando ahí asistí a varias escuelas hasta cerca de los diecisiete,
tiempo durante el cual pasé por mucha aflicción y prueba en mi mente.
Pero aunque yo vivía con una familia malvada y entre
personas que se mofaban de toda seriedad en la religión,
aun así,
a menudo me metía en algún lugar escondido y oraba o lloraba
amargamente por la consciencia de mis propios pecados,
y con frecuencia reprendía a mis compañeros de escuela y amigos por su maldad.
Muchas veces caminaba solo en lugares secretos cuanto
el resto estaba ocupado jugando o en pasatiempos.
De esta manera pasé mis días de juventud,
leyendo y en frecuentes oraciones cuando la aflicción estaba sobre mí,
de la que rara vez estuve libre por semanas enteras,
fuera de noche o de día. Durante ese tiempo no oí muchos sermones,
pues no estaba familiarizado con nadie que frecuentara tales prácticas,
hasta que llegué a ser aprendiz, aproximadamente a los diecisiete años.

Por ese tiempo fui ubicado en una parroquia en Londres,
en la que había un ministro que era llamado '`puritano.`' Ahí conocí
a un grupo de jóvenes que frecuentaban sermones y conferencias,
y asistíamos tan a menudo como teníamos alguna libertad de nuestro aprendizaje.
Sin embargo, a medida que crecía en el conocimiento y entendimiento de las cosas de Dios,
la aflicción crecía sobre mí más y más. Yo me dediqué
a leer la Biblia y otros buenos libros,
y a orar con frecuencia,
al punto que la familia con la que estaba entonces como aprendiz lo notó,
y en algunas ocasiones permanecían en lugares ocultos para oírme orar,
aunque en ese momento yo no lo sabía.

Pero recuerdo que cuando era más ferviente en mi devoción,
algo dentro de mí seguía refrenándome,
para que no dejara por completo los males de los que me sabía culpable.
Me habría gustado tenerlos perdonados y borrados, y aun así, deseaba continuar en ellos.
Había algo en mi interior que se oponía a mis más fervorosos clamores y peticiones,
y que deseaba tener tanto paz con Dios,
como continuar en aquellas cosas contra las que oraba.
Esto al final me hizo concluir que yo no era más que un hipócrita,
y que no tenía parte en la elección de gracia,
sino que me iba a convertir en un espectáculo eminente de la condenación de Dios.
Además, concluí que lo que se oponía a mis más fervientes clamores a Dios era el diablo,
y por tanto, que estaba poseído por él. Como resultado de esto,
tan frecuentemente como tenía oportunidad,
interrogaba a los otros profesantes cristianos acerca de cómo les iba a ellos,
y qué entendían de la condición de aquellos que estaban poseídos por un espíritu inmundo.
Pero todo lo que obtenía de ellos,
no quitaba de mi mente la idea de que estaba poseído por el diablo.
En realidad,
yo creía sentir en mí algo discernible y abiertamente opuesto
a las buenas intenciones y deseos que estaban en mí,
como si dos contrincantes estuvieran peleando en mí por la victoria.
Y cuando estaba muy cansado de resistirme y luchar,
no podía obtener alivio o perceptible tranquilidad, excepto al ir a orar;
fuera secretamente en mi interior o de rodillas en algún lugar escondido.

Muchas veces, cuando estaba orando,
me poseía tal temor que me detenía y miraba detrás de mí,
en caso de que el diablo estuviera ahí listo para llevarme tan pronto como me levantara.
Y luego me afligía por ceder ante mis temores y mirar hacia atrás. A pesar de todo esto,
no me atrevía a dejar de orar.
Pero lo que más me afligía era que aquellos que me escuchaban,
admiraban mi don en la oración y creían que era un hijo de Dios,
cuando mi conclusión acerca de mí mismo era que los estaba engañando,
e iba a provocar que el nombre de Dios fuera blasfemado por mi caída al final.
Porque yo creía que era imposible para mí continuar por mucho tiempo en esa condición,
antes de caer y ser hecho un ejemplo para todos los hipócritas.

Así continué profesando, orando, oyendo, leyendo, y sin embargo,
no podía percibir en mí ninguna verdadera mejora, más bien,
las mismas vanidades juveniles seguían arrastrando
mi mente cada vez que se ofrecía la oportunidad.
Yo nunca me entregué a actos externos groseros y profanos,
sólo a conversaciones frívolas, vanas compañías, pérdida de tiempo,
envanecimiento por mi ropa y cosas semejantes, por todo lo cual era condenado;
como también por usar el pelo largo y gastar mi dinero en vano,
el cual habría sido mejor empleado si hubiera sido usado para comprar buenos libros,
o darlo a los pobres.
Todo lo que hacía era condenado, y yo mismo por hacerlo, aun así,
no me atreví a dejar mis deberes religiosos,
porque pensaba que entonces el diablo prevalecería sobre mí y me obligaría a destruirme.
¡Oh, sí, yo tenía miedo de ver un cuchillo si estaba solo,
o de tener uno toda la noche en la habitación donde dormía!

Por lo tanto,
continué corriendo a escuchar conferencias cada vez
que mi maestro me otorgaba algún tiempo,
el cual yo me esforzaba por obtener duplicando mi diligencia
durante el día y absteniéndome de dormir durante la noche.
Yo buscaba reuniones y conferencias privadas,
e iba a escuchar a cualquier orador eminente del que había oído hablar,
porque para este momento yo había obtenido un gran conocimiento de tales oradores,
por estar muy familiarizado con oyentes de sermones y con
los que frecuentaban ayunos y reuniones privadas.

A veces, mientras escuchaba sermones,
tenía mucha dificultad para no gritar en medio de la asamblea:
"`¡Estoy maldito! ¡Estoy maldito!`"
Nunca lo hice, pero sí me iba lleno de horror y miseria en mi mente.
Los ministros en aquellos días comúnmente predicaban de
cómo podía saber un hombre si era un hijo elegido de Dios;
por medio de ciertas marcas y señales si lo era, y por medio de otras si no lo era.
Esto a veces me hacía concluir que yo tenía la gracia salvadora,
y otras que no era más que un hipócrita.
De esta manera era lanzado arriba y abajo, pasaba de la esperanza a la desesperación,
y de una señal de gracia en mí en una ocasión,
a una de señal de hipocresía y condenación en otra.
Yo no sabía qué hacer, si era mejor ir a la iglesia o quedarme en la casa,
porque no encontraba descanso o paz duradera por medio de todo lo que oía,
ni por correr de aquí para allá. No sentía libertad de acudir a ninguno
de esos ministros en privado y ponerlo al tanto de mi condición,
en parte, porque pensaba que no podían ayudarme, y en parte,
por temor a que me fueran a desanimar y a decirme que era un hipócrita,
y entonces Satanás prevaleciera y me obligara a destruirme.
¡De hecho,
tenía temor de cualquier cosa que pudiera confirmar mis
propios pensamientos acerca de mi miserable estado!
Porque mis propios pensamientos ya eran suficientemente malos,
y yo estaba extremadamente temeroso de que mis pensamientos
fueran secundados por el juicio de algún otro.
Así que nunca fui a ningún ministro para contarle mi condición,
sino que la cargué secretamente en mi propio pecho,
y pocos sabían lo que estaba pasando conmigo.

En una ocasión cuando era aprendiz y estaba lleno de aflicción,
decidí salir en la tarde del primer día (llamado el día del Señor),
y dirigirme hacia cualquier dirección que sintiera
que era movido o inclinado en mi espíritu,
ya fuera subir o bajar la calle, este u oeste, norte o sur,
sin ninguna determinación previa o premeditación,
sino "`donde me llevara el viento`" (por decirlo así) o fuera conducido.
Así que caminé guiado por algo en mi interior en lo que creía,
hasta que me llevó a una llamada '`iglesia parroquial.`' Entré y me senté,
y en un corto tiempo un joven subió al púlpito y predicó de Isaías 50:10,
"`El que anda en tinieblas y carece de luz, confíe en el nombre de Jehová,
y apóyese en su Dios.`"
Él había predicado antes sobre este versículo,
y en esa ocasión se propuso mostrar quién era ese hombre que temía al Señor,
y aun así andaba en tinieblas.
Él hizo esto como si hubiera conocido mi condición y hubiera hablado directamente conmigo,
lo cual me alivió enormemente.
En ese momento fue de gran consuelo, pues había sido llevado ahí providencialmente,
a un lugar donde nunca había estado antes.

Salí de ahí muy contento y continué así por un tiempo.
Pero la aflicción pronto vino sobre mí otra vez,
a través de cierta negligencia y frialdad, lo cual produjo desconfianza e incredulidad.
De modo que, el antiguo enemigo, el tentador,
entró de nuevo y me afligió en mi mente peor que antes,
de tal manera que me pregunté si todo lo que se me
había dado para refrescarme no era más que un engaño,
sin ninguna verdad en ello.
Entonces, el horror me llenó a tal punto que se me fue el sueño,
y una angustia e intolerable tribulación empezó a habitar en mi carne.
Y cuando escuchaba a algunas de las personas más
bajas y pobres que clamaban en las calles de Londres,
incluso deseaba que esa fuera mi condición,
porque pensaba que cualquier hombre o mujer estaba en mejores condiciones que yo.
Realmente yo me creía el único hombre miserable en el mundo.
Si yo me hubiera convertido en la criatura más despreciable de toda la creación,
habría sido feliz, en comparación con mi más intolerable miseria.
Todo esto se vio aún más acentuado por el libro de Francis Spira^
footnote:[Francis Spira (1502--1548) fue un abogado italiano convertido al protestantismo,
que bajo la presión de la Inquisición Católica negó sus
propias convicciones y públicamente se retractó de su fe.
El libro al que hace referencia Crook se llama,
"`A Relation of the Fearful Estate of Francis Spira`"
(Un relato del estado de terror de Francis Spira),
en el que se cuenta del terror que se apoderó de
Spira tras su retractación y la subsecuente culpa,
horror y angustia mental que pronto acabaron con su vida.]
que había llegado a mis manos, pero cuando había leído un poquito,
lo eché de mi lado y no me atreví a mirarlo más,
pues yo pensaba que se asemejaba mucho a mi condición.

Continué en esa extrema miseria, guardándola para mí y lamentándome en secreto,
hasta que una mañana,
mientras estaba sentado solo y lamentándome por mi estado del momento,
repentinamente se levantó una voz diciendo: "`¡No temas,
oh fatigado con tempestad y sin consuelo!
Yo te ayudaré, y aunque por un momento he ocultado Mi rostro de ti, aun así,
con misericordia eterna te visitaré y serás Mío. No temas, porque te he perdonado,
y nunca te dejaré ni te desampararé, dice el Señor, el Dios poderoso.`"

Entonces, súbitamente, todo se silenció y se tranquilizó dentro de mí,
de modo que me pregunté adonde se habían ido las muchas aflicciones,
temores y pensamientos que justo antes me atormentaban.
Hubo tanta calma y quietud en mi mente por un espacio de tiempo,
que recordé el silencio que se había producido en el cielo por media hora.
Estaba lleno de paz y gozo, completamente abrumado,
y brillaba tal luz interior dentro de mí,
que por un espacio de siete u ocho días caminé como si hubiera sido tomado de la tierra.
Estaba tan arrebatado en mi mente, que era como si caminara por encima del mundo,
sin prestar atención (según me parecía) a ninguna persona o cosa mientras
caminaba para arriba y para abajo en las calles de Londres,
pues estaba enteramente absorto en la maravillosa luz del Señor y lleno
de una especie de dominio gozoso sobre todas las cosas en este mundo.
En este tiempo vi claramente (y para mi gran consuelo y satisfacción),
que cualquier cosa que el Señor quisiera comunicar,
o dar a conocer de Sí mismo y de los misterios de Su reino,
lo haría en un camino de pureza y santidad.
Sí, entonces vi gran brillo en la santidad, gran belleza en la vida recta, pura y justa,
y en el andar cercano y sobrio con Dios en conducta santa.
Aunque yo antes había obedecido lo mejor que había podido, nunca había encontrado la paz,
la aceptación ni la justificación ante Dios que ahora sentía,
cuando surgía libremente en mí. Entonces vi que la
verdadera religión radica en esta comunión,
y que toda profesión de religión sin esto no era nada en comparación. Recuerdo bien,
que mientras permanecí y caminé en esa luz y gloria
que brillaban muy claramente en mi mente y espíritu,
no hubo un pensamiento erróneo que apareciera o luchara dentro de mí,
que no fuera rápidamente desvanecido por no recibir aceptación. De hecho,
mi mente y mi alma estaban completamente cautivadas,
y habían sido absorbidas por esa gloriosa luz y satisfactoria
presencia del Señor así manifestadas en mí.

Durante ese tiempo, cuando estaba lleno de gozo y paz,
descubrí que no podía realizar los deberes religiosos tan formalmente como solía hacerlos,
sino que, en su lugar, los hacía con mucha más vida y celo, fe y confianza, que antes,
lo que hizo que muchos de mis conocidos admiraran mi don en la oración,
y en algunas ocasiones me impusieran ese deber.
Pero después de ese tiempo,
percibí una reducción de la gloria y empecé a leer
y a realizar los deberes como los había hecho antes.
Por esa época empecé a seguir a algunos ministros que venían de Holanda,
y a algunos otros que se habían separado de las asambleas parroquiales;
porque me disgustaban esas asambleas mezcladas,
y sentía mucha sed y anhelaba la comunión pura con aquellos que eran más espirituales.
Habiendo visto algo de la belleza de la santidad,
yo anhelaba caminar con los que experimentaban una comunión con Dios en santidad,
y se vigilaban unos a otros para bien y para el incremento de la vida santa.

Caminé en compañía de algunos jóvenes,
y nos reuníamos tan a menudo como teníamos oportunidad,
y orábamos y conversábamos acerca de las cosas de Dios.
Recuerdo que cuando varios hablaban de las Escrituras, a modo de exposición,
yo tenía muy poco que decir,
pues en ese entonces no tenía mucho conocimiento de la Biblia,
pues había sido criado en familias y bajo tutores
que no habían considerado mucho las Escrituras.
Pero yo hablaba de mis propias experiencias,
y me deleitaba y amaba mucho a los que podían hablar por experiencia.
Sí,
mi corazón se sentía muy animado y avivado por aquellos
discursos y conversaciones de experiencias,
de modo que aquellos que eran más espirituales estaban
encantados de estar conmigo y yo con ellos.
Ellos a menudo me decían que yo hablaba por experiencia,
y que podía hablar de muchas condiciones y cosas como si
tuviera un tomo escrito dentro de mí de todos los temas,
mientras que la mayoría obtenía sus discursos de las Escrituras externas a ellos.

Pero en el lapso de dos o tres años,
comencé a amontonar Escrituras en mi mente y memoria
(tanto por oír a otros como por mis propios estudios),
lo que me llevó a morar más en el exterior y menos en el interior.
Y así, gradualmente, el conocimiento en mi entendimiento y juicio naturales,
empezó a superar y a sobrepasar el sentido de mis experiencias internas.
Al final,
teniendo poco más que el recuerdo (entonces muy lejano)
de aquellas cosas que una vez habían sido vivas y frescas,
y que habían crecido en mí como si fuera primavera en mi corazón y en mi mente,
ahora mi interior se había vuelto invierno.
La vida interior se retiró de la vista, como si estuviera en una raíz oculta,
y luego se empezaron a levantar en mi mente muchas preguntas acerca
de la forma de adoración y de las ordenanzas del Nuevo Testamento.

Ya que el Señor había hecho mucho por mí,
juzgué que no podría evitar ser culpable de ingratitud delante de Él,
si no buscaba entonces la forma más pura de adoración. Por tanto,
después de haber caminado entre varios tipos de profesantes cristianos de diversos juicios,
buscando con quién podía sentarse mi espíritu y unirse,
al fin me reuní con un grupo de Independientes con quienes me uní
en comunión. Pasamos muchos tiempos refrescantes juntos,
mientras nos mantuvimos vigilantes y tiernos,
con nuestras mentes internamente retiradas y con palabras escasas y sazonadas.
Fuimos preservados en este espíritu comunicando nuestras experiencias entre sí,
en cuanto a si nuestros corazones habían sido mantenidos hacia el Señor toda la semana,
y qué había pasado entre Dios y nuestras almas de principio a fin de la semana.

Así continuó por algunos años, hasta que se hizo formal.
Entonces empezamos a considerar nuestro estado:
si estábamos en el orden correcto del evangelio en concordancia con el patrón primitivo,
y en la administración apropiada del bautismo, etc.
Poco a poco empezamos a dividirnos y a dispersarnos
en nuestras mentes con respecto a estas cosas,
y se levantaron muchas preguntas acerca de diversos
temas que no se habían cuestionado antes,
todos los cuales tendían mucho a la incertidumbre e inestabilidad.
Luego, no sólo comenzamos a ser descuidados con respecto a nuestras reuniones,
sino también a confundirnos en nuestra predicación y servicio cuando nos reuníamos.
Finalmente dejamos de reunirnos y gradualmente nos fuimos alejando unos de otros,
y nos volvimos descuidados al considerar principios
de libertad y comodidad para la carne,
y de ahí caímos en la trampa de alentar y justificar nuestro
presente descuido y frialdad en la religión. No obstante,
yo no estaba tan entregado a la comodidad que no sentía
las correcciones ni las reprensiones por hacerlo,
y a menudo la aflicción y angustia internas en mi espíritu
me levantaban nuevamente a los deberes religiosos,
tales como orar y leer.

Cuando era oprimido en mi juicio y entendimiento natural acerca de doctrinas
y principios (opresión que se presentaba en mi estado débil y quebrantado),
descubrí que mi mente era arrastrada al descuido con respecto a todo aspecto de la religión,
y despreciaba mi seriedad anterior contra el pecado y el mal.
Vi cuántos principios y doctrinas existían que me habrían llevado a creer
que mi comprensión anterior acerca de la maldad y el gran peligro de esta,
surgía de mera emoción o tradición, y no de razones fundamentadas o juicio verdadero.

Fui frecuentemente ejercitado de día y de noche,
y tentado (tanto por sugerencias internas como por
atracciones externas) a abrazar tales principios.
En algunas ocasiones, otros que habían sido tan religiosos como yo,
y que no estaban menos familiarizados con experiencias internas del mismo tipo,
trataron de alejarme del sentido y profunda impresión de la Verdad que permanecía sobre
mi espíritu después de las grandes aflicciones y consolaciones que había gustado.
Pero el palpable recuerdo de los días anteriores se mantenía sobre mí,
y me guardó de los principios del ranterismo^
footnote:[Los Ranters eran un grupo no conformista que surgió a mediados de los 1600,
y que recibieron su nombre debido a sus extravagantes discursos y prácticas.
Algunos de ellos parecen haber sido genuinos buscadores de la verdad,
quienes (en palabras de William Penn),
"`no se mantuvieron en la humildad ni en el temor de Dios,
y después de abundante revelación, se exaltaron,
y por falta de mantener sus mentes en humilde dependencia de Aquel que había
abierto sus entendimientos para que vieran las grandes cosas de Su ley,
corrieron en sus propias imaginaciones y las mezclaron con las revelaciones divinas,
dando a luz un monstruoso nacimiento para escándalo de aquellos que temían a Dios.`"
Los Ranters a menudo interrumpían las reuniones religiosas
establecidas vociferando a gritos,
cantando, tocando instrumentos o haciendo toda clase de ruidos fuertes.]
y ateísmo que prevalecían y causaban gran conmoción en aquellos momentos.

A través de la fe en lo que había gustado,
fui sostenido cuando estaba bajo muchos amargos combates,
y profundas ondulaciones y olas, y llegué a la conclusión en mi corazón y en mi mente,
de que '`el justo era más excelente que su prójimo,`'^
footnote:[Traducción literal de la KJV de Proverbios 12:26]
y que había una mucho mejor condición que experimentar y disfrutar
en este mundo al caminar con Dios en santidad y pureza,
que todo lo que se encuentra en una vida licenciosa y sensual,
o por medio de la codiciosa acumulación de riquezas
con tal de obtener un nombre en esta tierra.
Esto lo sabía por la dulzura que yo había disfrutado anteriormente,
y por el recuerdo que permanecía debajo de todos los razonamientos
y observaciones secas que podía hacer.
Sí,
yacía más profundamente alojada en mi interior que
todas las comprensiones que flotaban en mi mente.
Así descubrí que había un continuo clamor y sonido en mis oídos internos,
que me llamaban a vigilar mis caminos y a obedecer lo que había
sido manifestado en mi consciencia como la voluntad de Dios.
Vi que era más probable que esto me proporcionara más descanso y paz,
que todos mis conceptos, observaciones, creencias o sacrificios.

Pero el verdadero significado de estas cosas me era desconocido y no lo entendí claramente,
hasta que le plació al Señor enviar a uno de Sus siervos, de los llamados cuáqueros,
a ministrarme como lo había hecho Felipe con el eunuco en el carro.
Porque el eunuco no entendía lo que leía,
pero después de que Felipe le explicó las Escrituras, creyó en aquello que ignoraba.
Así sucedió conmigo,
pues a través del siervo e instrumento del Dios altísimo que abrió
mis ojos y habló con sencillez (no con parábolas o dichos oscuros),
llegué a ver qué era eso que había clamado por tanto tiempo en mí,
en cada ocasión de serio retiro interior en mi propio espíritu.
Entonces pude decir de Cristo al fin:
"`Uno mayor que Salomón en este lugar;`" mayor que aquel
que había discernido correctamente entre lo vivo y lo muerto,
y manifestado claramente a quién pertenecía el niño vivo.
Sí, Él fue el que reveló a la verdadera mujer, o iglesia,
la cual está en Dios el Padre de nuestro Señor Jesucristo,
y también dio a conocer quién era la ramera, o falsa iglesia y sinagoga de Satanás,
sin importar lo que ella pudiera decir para justificarse como la verdadera madre iglesia.

Cuando escuché por primera vez este tipo de predicación,
por el llamado cuáquero anteriormente mencionado,
me pareció como si los antiguos apóstoles se hubieran levantado
de la muerte y comenzado a predicar de nuevo en el mismo poder,
vida y autoridad en que ministraron y publicaron el nuevo pacto de Jesucristo al principio.
Y verdaderamente pude decir con Jonatán,
después de haber oído y gustado la miel y dulce ministración del bendito evangelio,
que mis ojos habían sido abiertos y mis fuerzas renovadas,
a partir del mismo poder por el que el evangelio había sido predicado al principio;
pues este evangelio estaba libre de los contaminantes
y residuos del ingenio y los inventos del hombre,
por medio de lo cual el hombre, al usar palabras sin conocimiento,
había oscurecido por mucho tiempo el consejo.
Digo la verdad y no miento.
Después de haber oído y gustado la miel de Canaán que fluía libremente,
sin las forzadas invenciones del cerebro del hombre,
mis ojos fueron abiertos y mis fuerzas renovadas.
Entonces, a través de la gracia del evangelio,
obtuve la victoria sobre aquellas lujurias y deseos corruptos que se levantaban
contra las pequeñas agitaciones y movimientos en mi corazón en pos del
Dios vivo (eso que yo había sentido a veces obrando en mí,
incluso desde mi juventud).

Cuando las buenas nuevas del evangelio sonaron en
mis oídos y alcanzaron mi corazón y consciencia,
no anularon mis anteriores experiencias del amor
y misericordia de Dios hacia mi pobre alma,
ni llevaron mi mente a despreciar en lo más mínimo
Sus dulces refrescamientos durante mi cansado peregrinaje,
los cuales eran como corrientes de aquel arroyo del
que Israel había bebido en el trayecto de sus viajes.
Por el contrario,
refrescaron en mi memoria las muchas maneras en que
el Señor me había revivido en mi dolorosa esclavitud,
manifestaron mis múltiples rebeliones contras Sus invitaciones,
y mi ingratitud hacia Sus tiernos tratos y las frecuentes visitas que me había hecho.
Esto produjo una verdadera sujeción de mi parte,
como el deber más grande hacia este tierno Dios y Padre.
Dichas buenas nuevas me hicieron gritar: "`¿Qué,
estaba Dios en este lugar y yo no lo sabía?`" (Génesis 28:16) Entonces experimenté
mi corazón quebrantado y vencido por Su amor y misericordia hacia mí,
y me volví más tierno delante de Él.

De este modo me fueron traídas a mi memoria todas las cosas,
y llegué a conocerlo no sólo como Aquel que "`me
dijo todo lo que había hecho`" contra Él,
sino también todo lo que Él había hecho por mí. Esto hizo
que la Verdad fuera aún más preciosa y aceptable en mi corazón,
pues trajo en un nuevo recuerdo las cosas viejas y restauró
una vieja relación con mi largamente provocado Dios.
En realidad, sucedió conmigo como había sucedido con Natanael,
quien confesó a Cristo tan pronto como Él le dijo que lo había visto debajo de la higuera.
De igual manera, no pude retener la sujeción inmediata de mi alma a la Verdad,
cuando vi cómo me había examinado a fondo y manifestado dónde estaba ahora,
y cómo había visto y visitado Dios mi pobre alma varias veces.
Por tanto, he encontrado la promesa de Cristo a Natanael cumplida en mí también,
pues desde el día de la visitación, he visto cosas mayores que las que alguna vez vi.

Luego vi que mi condición anterior (antes de que la Verdad me conquistara
completamente y se manifestara claramente) era como la de Agar,
quien tenía pan y un odre de agua que le había dado Abraham,
tras ser enviada al desierto por las burlas de su hijo a Isaac.
Cuando el pan y el odre de agua se acabaron,
la condición de Agar y la de su hijo fue aún más miserable;
ella no tenía manera de llenar el odre de nuevo, ni pudo ver la manera,
aunque no estaba lejos de ella.
Pero su necesidad llegó a los oídos de Dios y Él le abrió los ojos,
y entonces vio "`el pozo del Viviente que me ve.`"
Así fue conmigo cuando el pan y el agua de alivio (que Dios
a menudo me daba para mantenerme en el desierto) se acabaron;
era probable que pereciera al no ver ningún pozo o forma de suministro.
Pero el Señor envió al ángel de Su faz para que abriera mis ojos,
y vi mi "`pozo del Viviente que me ve,`" el cual estaba ahí antes,
pero no había podido verlo hasta que mis ojos fueron abiertos.

Así, pues, por falta de entendimiento (junto con muchos otros),
languidecí muchos de mis días, al igual que Agar en el desierto,
como castigo por mi liviandad y por haberme unido con Ismael en el desprecio hacia Isaac,
la Semilla verdadera en mi propio corazón,
y heredera de todas las bendiciones espirituales;
Aquella con quien Dios establece Su pacto para siempre.

De esta manera fui convencido de la Verdad hacia el final del año 1654 (según recuerdo),
a través del siervo del Señor antes mencionado, William Dewsbury.
Yo no sabía a cuál convicción pertenecía él cuando lo fui a oír,
porque si hubiera sabido que era de los cuáqueros, creo que no lo habría escuchado,
pues temía ser engañado por opiniones extrañas. Pero al
ser providencialmente llevado al lugar donde él estaba exponiendo,
oí sus palabras, las cuales eran tanto lanzas que perforaban y herían mi corazón,
como un bálsamo que me sanaba y consolaba.
Recuerdo las palabras precisas que más me impresionaron en aquel momento.
Hablando de los varios estados y condiciones de los hombres y mujeres,
describió la miserable vida de los que, a pesar de sus deberes o desempeños religiosos,
no tenían paz ni tranquilidad en sus espíritus,
ya que debido a la falta de entendimiento de dónde buscar
un ancla para sus mentes en todo momento y en todo lugar,
eran como niños llevados de aquí para allá,
atemorizados por la calculada astucia de los hombres
que promovían sus propias opiniones y formas.
En ese momento supe que esa era mi condición,
como también el estado de muchas otras pobres y destrozadas personas,
que estábamos '`rodeadas por las teas de nuestro propio fuego.`' (Isaías 50:11) En realidad,
este no nos había traído más que dolor cada vez que nos acostábamos,
cuando estábamos callados, meditando en nuestra cama,
pues no teníamos nada internamente para alimentar y anclar nuestros corazones,
además de los deberes formales que perecen con el uso,
o las discusiones acerca de cosas doctrinales en el entendimiento y memoria naturales.
Esto lo vine a saber y a observar después,
en la aparición de la principal Piedra del ángulo puesta en Sión,
escogida y preciosa para los que creen en Ella.
En Su luz ciertamente entendí, que no es una opinión sino Cristo Jesús,
el poder y brazo de Dios, quien es el Salvador.
Y cuando Él es sentido en el corazón y se mantiene morando ahí mediante la fe,
Él se distingue de todos los conceptos en el cerebro,
como se distingue la sustancia viva de un cuadro o imagen de ella.

El recibimiento de la Palabra de vida en mi alma,
fue como el librito que le fue ordenado a Juan comer,
el cual resultó ser dulce en su boca, pero amargo en su estómago.
Así fue la Verdad para mí, tan dulce y deliciosa en mi paladar,
como lo fue la miel para Jonatán,
por medio de la cual mis ojos fueron abiertos y mi fuerza renovada con gran gozo y claridad.
Así continuó por algunos meses después de la primera vez que oí,
mediante lo cual mi juicio fue tan ensanchado y fortalecido contra
todas las baterías y asaltos de los disputadores de este mundo,
que no me cabe la menor duda de que habría podido mantener
los principios de la Verdad contra todos los opositores.
Sin embargo, todo ese tiempo consideré poco la forma o expresión externa de la Verdad,
hasta que oí a la misma persona declarar la palabra de Verdad otra vez.
Entonces comencé a ver que todo el conocimiento era nada,
sin la verdadera práctica y conformación a lo que sabía. Y entonces
la Verdad empezó (como el librito) a ser amarga en mi interior,
debido a que yo no estaba rindiendo obediencia a
lo que estaba convencido que era mi deber;
como dejar de lado toda la extravagancia en la vestimenta, palabras y conducta,
lo cual era para mí difícil de hacer,
estando en ese entonces comisionado como Juez de Paz.
Pero poco a poco,
fui llevado a través de todos los cuestionamientos y razonamientos al respecto,
por medio de dolorosos y agudos terrores en mi consciencia.
Llegué a ver todos mis pecados y maldades (tanto externos y grandes,
como secretos y escondidos) por medio de la luz en mi propia consciencia,
y supe que todos mis pecados no eran sino combustible,
que la ira e indignación del Señor debía consumir.

Vi que el hacha tenía que ser puesta a la raíz del árbol,
y que había una naturaleza maligna que debía ser consumida en mí,
la cual había dominado durante mucho tiempo, a pesar de mi profesión religiosa.
Vi que mi extravagancia en la vestimenta, en las palabras y en muchas otras cosas,
no hacía más que alimentar y mantener viva esa naturaleza,
y que así prolongaba el fuego para mi propia gran miseria.
Entre muchas otras cosas vi claramente,
que hablar de manera diferente a ciertas personas,
y quitarme el sombrero según la costumbre y moda del mundo,
debía ser dejado y rechazado antes de que esa naturaleza
carnal y mundana muriera en mí por completo,
y yo fuera perfectamente liberado de ella.
Claramente vi que esas cosas,
junto con el uso de muchas palabras fuera del temor de Dios,
no eran más que comida que nutrían,
alimentaban y mantenían viva la naturaleza y parte equivocadas en mí.

¡Oh, cuán fuertemente me resistió la razón carnal,
en mi separación de estas y otras cosas!
Nadie lo sabe, sino aquellos que han sido ejercitados de la misma manera.
Tampoco puedo expresar la multitud de maneras y argumentos que
usó el diablo para mantenerme en esas formalidades y costumbres,
mucho más por mis innumerables conocidos y mi empleo público.
No obstante,
la más grande tribulación que atravesé (antes de poder entrar en el reino de Dios),
fue desprenderme de mi propia sabiduría y conocimiento,
mediante lo cual yo me había beneficiado más allá de muchos de mis iguales.
Descubrí que necesitaba
ser decapitado (por decirlo así) por el testimonio de Jesús,
pues encontré por cierta experiencia,
que hasta que el hombre es verdaderamente crucificado con Cristo,
es capaz de dar un verdadero testimonio de Cristo.
Previo a esta muerte, el hombre sólo puede dar testimonio de sí mismo,
cuyo testimonio no es verdadero;
pero después de que es efectivamente crucificado con Cristo y levantado con Él,
si da testimonio de Cristo entonces, su testimonio es verdadero.
En esto, es correctamente entendido el dicho fiel:
"`Porque el testimonio de Jesús es el espíritu de profecía`" (Apocalipsis 19:10).

Después de una larga y aguda lucha de aflicciones
y profundos ejercicios en mi corazón y consciencia,
al fin me rendí para ser un tonto para Cristo,
como el que está "`loco para el Señor`" (2 Corintios
5:13). Esto se efectuó con profunda agonía,
porque yo realmente llegué a pensar que podía perder mi mente debido
a los terrores de Dios que estaban sobre mi alma.
Pero al fin, por Su gracia, Él sujetó el espíritu de mi mente a Sí mismo,
para que a través de Su predominio yo cediera y estuviera quieto,
y Él pudiera hacer conmigo lo que deseaba.
Entonces fui capaz de rendirme a la muerte del hombre, mente y sabiduría carnales,
lo cual fue como la muerte del primogénito en Egipto.
Y luego me fue dicho: "`De Egipto llamé a mi hijo;`" aquel que antes estaba muerto,
pero que ahora vive para Dios en Su pacto eterno, para siempre.

Así llegué a conocer a Aquel en quien no hay ocasión de tropiezo.
En efecto, Lo vi ser el que silencia al disputador y sabio de este mundo,
respondiendo de manera plena y muy satisfactoria al profundo
clamor y necesidad que estaban en mi alma.
Sí, Él llegó a ser para mí como una lluvia muy dulce,
la cual alcanzó hasta la raíz en mí,
y vi que todas Sus vivificaciones anteriores no eran más
que gotas de verano que provocaron una mayor sequía después,
o como un viajero que sólo se quedó una noche.
Mientras continuaba en mi viaje espiritual,
experimenté el cumplimiento de estos y muchos otros dichos de las Escrituras,
los cuales fueron como un arroyo en el camino,
que muy dulcemente alegraron mi alma en la medida que el Señor me hacía beber de ellos.
El Señor puso una copa en mi mano y Él mismo era mi porción.

No debo olvidar relatar de mi travesía, como después de llegar al Monte Sinaí,
sentí el ardor de ese fuego que quemaba toda mi justicia propia como rastrojo y paja,
y vi que dicha justicia no era capaz de proporcionarme
refugio o preservación alguna de aquellas llamas.
Entonces pensé en confiar en el conocimiento que
había adquirido de Cristo al leer las Escrituras;
tal como, que Él era mi garantía,
y que Dios Lo había aceptado en mi lugar tras haber satisfecho la justicia divina.
Estos conceptos,
junto con las dulces experiencias que anteriormente
había tenido de Cristo antes de llegar a esta forma,
me hicieron decir en mi interior: "`¿Debo dejar todas estas cosas?`"
A cuya pregunta (y a muchos más razonamientos de la misma naturaleza) fue dicho en mí:
"`¿Fue un simple recuerdo de Cristo y de Sus méritos,
y la seguridad reunida o aplicada en tu propio tiempo
o por tu propio entendimiento natural,
lo que te salvó o ayudó en tu angustia?
¿O fue Mi gratuita revelación de Él como Mi brazo y poder dentro de ti,
por lo que realmente sentiste consuelo en tu interior,
de la misma manera que el pecado y el diablo eran
verdaderamente sentidos dentro de ti atormentándote?`"
Así llegué a saber cómo, cuando Cristo aparece,
la Semilla de la mujer alcanza el estado débil en que se encuentra el hombre, incluso,
cuando Satanás, la serpiente antigua,
está más ocupada levantando su cabeza para dominar y atormentar a la criatura.
Esta Semilla es también conocida como la Semilla de Dios, la cual,
por medio del Espíritu, hiere la cabeza de la serpiente y aniquila todo dominio,
para que Cristo pueda ser el Príncipe y Salvador para siempre.

De esta manera llegué al conocimiento salvador de Cristo,
el cual confirmó mi anterior experiencia de Su aparición en mí y a mí,
incluso cuando era débil en mi entendimiento y no tenía
más que comprensiones carnales de Él. Sin embargo,
el verdadero Cristo salvador de Dios es ciertamente vida, poder y virtud,
y aquellos que Lo conocen como tal,
tienen el conocimiento de la verdad como está en Jesús,
porque la opinión o el concepto de Cristo en el entendimiento
natural queda demasiado corto.
Pero cuando se le presta atención y se sigue a esta Semilla
en el interior (la cual batalla contra el pecado y el mal),
ella rectifica el entendimiento según el verdadero y correcto reconocimiento de Él,
quien es el verdadero Dios y vida eterna,
el Salvador mismo de todo aquel que cree en Él. Muchos sólo
llegan a ser enanos en lo que a experiencia se refiere,
por darle paso a la voluntad de ellos,
y no dejar que la luz en la consciencia mande y dirija el entendimiento y el juicio.
Estos rechazan dicha luz diciendo que es natural e insuficiente, y sin embargo,
(por la sutileza de la serpiente antigua) al mismo
tiempo siguen su propia voluntad y entendimiento,
los cuales son, de hecho, tanto naturales como insuficientes.

Así pasé del Monte Sinaí al Monte Sión,
del ministerio de condenación al ministerio del Espíritu, debido a lo cual pude,
y verdaderamente lo hice, dar gracias a Dios por medio de Jesucristo.
Él me liberó de esa condenación bajo la cual estaba,
a pesar de todos mis deberes y creencias,
y me llevó Al que es la suma y sustancia de todo,
y que ahora es mi regla y guía. Él fue el guía en mi juventud en muchas cosas,
aunque yo no lo sabía entonces.
Y ahora Él es para mí el Espíritu que da verdadera libertad de todo yugo de esclavitud,
pues el ministerio del Espíritu batalla contra la carne y es contrario a ella,
y el alma que camina según el Espíritu disfruta de vida en abundancia;
pero si el espíritu de este mundo prevalece,
entonces la muerte y la condenación regresan.
Hallé que es tal como está escrito:
"`Y los que viven según la carne no pueden agradar
a Dios,`" y "`porque si vivís conforme a la carne,
moriréis.`"

Después de esto sentí que el Espíritu de verdad gobernaba en mí,
y que mi espíritu realmente estaba en unión con Él,
aunque antes había estado en unión con el espíritu de este mundo.
A partir de ese momento,
el Espíritu de verdad se convirtió en la verdadera regla
por la que yo caminaba y era guiado a la paz y reposo,
así como antes, cuando el viejo hombre gobernaba, era conducido a la angustia y dolor.
Así fue claramente demostrado en mí,
que '`la estabilidad de tus tiempos son justicia y paz.`' De igual manera,
esta otra escritura fue cumplida también en mí:
"`Porque en Cristo Jesús ni la circuncisión vale nada, ni la incircuncisión,
sino una nueva creación.`" Sólo aquellos que son contados como la simiente,
el Israel de Dios, y caminan de acuerdo con esta regla, heredan la verdadera paz.

Cuando sentía el nacimiento inmortal levantarse en mi interior,
como una planta deliciosa,
a menudo sentía que producía muchas respiraciones dulces y celestiales en pos de Dios,
las cuales eran frecuentemente respondidas por Él, por lo cual,
nunca busqué Su rostro en vano, ni pedí sin recibir una respuesta satisfactoria.
También descubrí que las alabanzas y acciones de gracias se alzaban
y brotaban naturalmente hacia Dios desde la raíz santa,
de la misma manera como antes había experimentado una naturaleza
malvada e iracunda lanzar fango e inmundicia,
y enviar temor, terror, dificultad y desconfianza.

Entonces mi gozo fue completo,
y a menudo se levantaba en mí un clamor a Dios pidiéndole
que me mantuviera pobre y bajo la cruz diaria de Cristo,
para que no fuera nada en mí mismo, sino libre de toda voluntad y obra propias,
dependiendo diariamente del Señor en este nacimiento puro,
y encontrándolo a Él ser la fuente y alacena de todo lo necesario.
Tanto solo como en las reuniones,
con frecuencia lo sentía a Él levantarse con gran poder y gloria,
constriñéndome a anunciar como una trompeta, las alabanzas vivas a mi Dios,
pues de la boca de esta Semilla de vida eterna brotaban palabras dentro de mí,
mientras estaba sentado en las reuniones con el pueblo de Dios (y en otros momentos),
que era movido a pronunciar con mi lengua.
Muchas veces hablé manteniendo mi propia voluntad bajo la cruz,
porque las palabras le parecían a mi sabiduría terrenal carentes
de sabiduría y a mi entendimiento natural muy despreciables,
y yo no sabía el fin por el cual debía decir esas palabras.
No obstante,
era culpado de desobediencia y profundamente afligido y perturbado en mi espíritu,
cuando me negaba a hablar.
A veces, mientras dudaba y razonaba acerca de ellas,
otro pronunciaba las mismas palabras, lo que era una gran prueba para mí,
al saber que las palabras habían sido tomadas de mí y dadas a otro que era fiel.

Después que le plació al Señor revelar a Su Hijo en mí,
me mostró las engañosas obras del "`hombre de pecado`" en mí mismo (en el "`misterio
de la iniquidad,`" 2 Tesalonicenses 2:7) y su exaltación en el templo de Dios,
donde él es adorado como Dios por encima de todo lo que se llama Dios.
Y vi, que aunque Dios merece toda adoración, aun así en este templo Él es poco conocido,
o poco notado por la criatura,
debido a la exaltación y gobierno de otra cosa que se ha aparecido como Dios,
pero que no lo es.
Todo esto lo vi en la luz del Señor. Y no sólo eso, pues también sentí por experiencia,
cómo levantaba Dios lo segundo, como al menesteroso del muladar,
y hacía que lo primero en mí lo sirviera.
Así llegué a conocer Al que es tanto Príncipe como Salvador,
y Ministro del verdadero tabernáculo que había levantado Dios y no el hombre.
Esto no lo experimenté en mí mientras el primer tabernáculo estaba de pie,
ni tampoco experimenté el Lugar Santísimo mientras el velo permanecía sobre mi corazón,
el cual descubrí quitado en Cristo, y que de ese modo,
un camino nuevo y vivo había sido abierto hacia el Lugar Santísimo.

El Señor me hizo ministro de este camino nuevo y vivo,
y me mandó a dar a conocer lo que había visto, sentido,
palpado y experimentado de la Palabra y obra de Dios.
Al principio fue difícil rendirme a esto,
al tener en mi mente muchos razonamientos y deliberaciones.
Por un lado,
temía que aquellos entre los que ministraba supusieran
que estaba actuando por mi propia voluntad,
por otro lado, temía ir a fijar reuniones, congregar personas,
y luego sentarme como un tonto entre ellos, sin tener nada que decir.
Estos y otros muchos razonamientos (siendo muy numerosos
como para mencionarlos específicamente) me asaltaban.
Pero sintiendo diarias agitaciones y movimientos de la vida,
y un mandato dentro de mí para ir a tal y cual lugar por nombre
(indicados por medio del Espíritu de Dios en mi interior),
me encontré con un resultado bendito, y muchos se convirtieron en ese momento,
quienes hasta el día de hoy permanecen en la verdad, y otros han muerto en la fe.
El recorrido y la extensión de los condados en donde
yo debía mayormente trabajar en la obra del Señor,
me fue mostrado por el Espíritu del Señor,
aunque viajé a otras partes también cuando el movimiento del mismo Espíritu
me lo requería. Y descubrí que no era capaz de contenerme,
sino que las palabras brotaban de mí en las reuniones donde
se me había ordenado ir entre el pueblo de Dios;
tanto en mi propio lugar de habitación como en otros lugares.
Me fueron revelados muchos territorios adonde debía ir,
y por haber sufrido profundamente por los juicios de Dios por desobediencia de este tipo,
me rendí a hacerlo sin vacilar.
En realidad, siempre encontré que Él era más grande en Su bondad de lo que yo esperaba,
y más abundante en el derramamiento de Su Santo Espíritu de lo que mi fe podía alcanzar,
incluso, hasta el quebrantamiento de mi corazón delante de Él en secreto muchas veces,
cuando ningún ojo me veía.

Omitiré todas las dificultades y pérdidas en cuanto
a mi familia y todos los asuntos externos,
a través de los cuales fui obligado a pasar cuando el Señor me conducía,
tanto por el dulce y quebrantador sentido de Su tierna misericordia hacia mi alma,
como por la consciencia de Su enojo y disgusto si yo desobedecía.
De modo que fui constreñido a obedecer al Señor en mi ir y venir,
según Él me enviaba, sin pensar en lo que debía decir,
sino clamando con frecuencia en mi espíritu: "`¡Mantenme pobre y necesitado,
creyendo en Ti, y entonces hablaré a partir de Ti y por Ti!`" ¡Oh, sí,
tengo grabada en mi consciencia la misericordia de Dios hacia mi alma,
cómo envió Él a Sus siervos de lejos para buscarme,
y predicarle el evangelio eterno a mi pobre y perdida alma!
Entonces, ¿por qué me rehusaría a ir y buscar a otros,
cuyas almas están perdidas como una vez estuvo la
mía? ¿No amaré a mi prójimo como a mí mismo?
Y yo, conociendo los terrores de Dios,
¿me negaré a persuadir a los hombres en nombre de Cristo (en obediencia
a Sus movimientos en mi alma) a que se reconcilien con Dios,
sabiendo que Él es fuego consumidor?
Tales eran las cavilaciones en mi mente y los
pensamientos en mi corazón cuando me rendí para ir adonde el Señor me dirigiera,
y nunca carecí de Su asistencia.
Sin embargo, algunas veces me sentía como el más débil de toda la reunión,
como una vasija vacía, sin una gota que dar para aliviar a alguien,
y me preguntaba qué había sido de todo mi conocimiento,
y por qué debía sentarme entonces como alguien en pobreza,
en una posición más acorde a ser ministrado que a ministrar a otros.
Pero aunque a veces no tenía nada que dar, aun así,
en lo que a mi propio estado se refiere no tenía carencia,
sólo que yo sentía que otros esperaban algo de mí, lo cual era una prueba para mi mente.
Sin embargo, gradualmente aprendí a morir a todo menos a la voluntad de Dios,
y a estar contento ya fuera en silencio o hablando.

Comencé a ministrar alrededor del año 1656,
después de haber estado algunos meses en la prisión de Northampton,
por estar en una reunión con el pueblo de Dios.
Ahí aprendí de la deidad, tanto mediante profundos sufrimientos externos,
como por ejercicios internos,
experimentando que los misterios sellados de Dios
eran abiertos a través del paso de ayes;
pues después de que pasaron el primero y segundo ay,
fueron abiertos nuevos sellos de los misterios de Dios.
De esta manera,
Dios hizo que las cárceles fueran como escuelas para los verdaderos
profetas o guarderías para los verdaderos ministros del evangelio.
Y luego, tras aprender a permanecer en mucho temor y pavor de Dios,
desde el profundo sentido que tenía de Su majestad y pureza en mi corazón,
hablé de Él cuando sentía que me lo pedía. Sus recompensas
estaban en mi seno como el más dulce y reconfortante licor,
que hacía que mi espíritu se elevara por encima de toda incomodidad,
tanto de los enemigos dentro como fuera.
Y aunque con frecuencia las pruebas me acosaban mucho, como abejas por todo lado,
aun así el bendito poder y presencia de Dios en mí y conmigo,
le proporcionaban a mi corazón y lengua palabras adecuadas
para las diferentes condiciones de los oyentes,
por encima de todo temor a cualquier cosa o persona presente.
Yo podría llenar un volumen con este tema,
pero lo que aquí es dicho es para la gloria del Todopoderoso Dios,
para el consuelo y ánimo de Sus ministros que permanecen en Su consejo,
y para la humillación de toda carne.
¡Qué toda confianza y dependencia descansen en la suficiencia del Santo Espíritu de Dios,
como el único proveedor para todo ministro y persona que salga en Su nombre!
Amén.

Este Santo Espíritu ha sido para mí tanto comida como bebida,
tal como la Roca de la antigüedad que seguía a los israelitas.
Diez veces (según recuerdo) he estado preso,
y no sólo he incurrido en la sentencia de "`premunire`"^
footnote:[Premunire era un juicio legal diseñado para privar de derechos civiles
a los que se rehusaban a jurar formalmente lealtad al rey de Inglaterra.
Los que quedaban bajo la sentencia de premunire eran considerados traidores
a su país. Perdían todos los derechos de propiedad y posesión,
eran sacados de la protección del rey, y a menudo, eran encarcelados de por vida.]
con mis hermanos en Londres, sino también he sido juzgado por mi vida en el campo,
y todo por el bien de una buena consciencia delante de mi Dios.
Sin embargo, este Santo Espíritu nunca me ha dejado,
sino que muchas veces me ha hecho cantar en las prisiones,
y a menudo me ha traído coraje fresco delante de mis acusadores.
De hecho, por Su virtud han sido detenidos jueces crueles,
y los testigos envidiosos que buscaban destruir al inocente han sido confundidos.
Sí, por este Santo Espíritu todo se ha vuelto alegría para mí. Mi ayuda está en Él,
mi consuelo fluye de Él,
y diariamente le pido a mi Dios que todo Su pueblo
sea guiado en todas las cosas por medio de Su Espíritu.
¡Oh, qué Dios sea adorado por siempre en Su propio Espíritu,
y Su bendita verdad predicada a través de Él, y que ni el ingenio, ni la habilidad,
ni el aprendizaje externo, ni dones, ni personas,
ni formas sean puestas o estimadas por encima de Él nunca! ¡Que los que hemos sido bautizados
en Su Espíritu siempre seamos hallados bebiendo de Él mientras estemos en el cuerpo,
para que cuando este cuerpo vaya llegando a su fin, podamos hacerlo con gozo,
tanto para alabanza de las riquezas de Su gracia,
como para el consuelo de los que nos sobreviven en la misma verdad!
Amén.

[.asterism]
'''

__John Crook fue un sabio comerciante en la casa del Señor,
que vendió todo lo que tenía para comprar la Perla de gran precio.
Aunque nació en una familia acomodada,
y por educación y dones naturales se convirtió en una prominente figura pública,
lo llegó a contar todo como estiércol en vista de
la excelencia del conocimiento de Jesucristo.
A través de muchos malos tratos, diez encarcelamientos y varias enfermedades prolongadas,
su espíritu fue guardado dulce, humilde y en verdadero temor del Señor, tanto así,
que después de su muerte uno que había sido su amigo por más de cuarenta años dijo:
"`Yo no recuerdo haberlo oído pronunciar una palabra desagradable o clamar impacientemente.`"__

__Poco antes de su muerte, acaecida a los 82 años,
escribió una epístola a sus hijos y nietos,
ofreciéndoles importante consejo a partir de una vida llena de profunda experiencia.
La carta empieza de la siguiente manera: "`Queridos hijos,
debo dejarlos en una época perversa,
pero los encomiendo a la medida de gracia de Dios en el interior de ustedes,
la cual han recibido por Jesucristo.
En la medida que la amen y obedezcan las enseñanzas de ella,
encontrarán un consejero que los instruirá en el camino
eterno y los preservará fuera de los caminos de impiedad.
He visto mucho en mis días y he observado que el temor del
Señor Dios siempre resultó ser la mejor porción,
y que aquellos que caminaron en él, fueron las únicas personas felices,
tanto en esta vida (mientras se mantuvieron fieles) como cuando llegaron a la muerte.`"__
